### ISSUE TITLE
resize video

### ISSUE THREAD

**Issue by tmikulski** [dbweb-ch/ioBroker.rtspstream#1]
Very nice adapter. It could be useful to resize video, e.g. in URL ?w=1280&h=720

Adapter works with "ESCAM QF509 1080P WiFi IP Camera"

**Comment by Yoyokeks** [comment]
https://imgur.com/a/2dX6eRZ
I had little free time to play with this great adapter.
To resize Video you have to add to ffmpegOptions: { // options ffmpeg flags 
 '-vf': ' scale=w=385:h=260:force_original_aspect_ratio=decrease'

**Comment by dbweb-ch** [comment]
Now integrated to add width and height.
