### ISSUE TITLE
Update / Remove not possible because of lower case name

### ISSUE THREAD

**Issue by Strobelix80** [dbweb-ch/ioBroker.rtspstream#10]
Because of the new name rtspstream instead of rtspStream i cannot update or remove instances now.
A new install from github shows up a new Adapter with the new name so I have two Adapters with different names

**Comment by dbweb-ch** [comment]
Did you try the tips from the forum?
https://forum.iobroker.net/topic/27302/test-adapter-rtspstream-v0-0-x-github/111?_=1611554859611
Otherwise please ask the question in the forum, I am not aware how the deinstallation routine on iobroker works and what could cause the issue.
