### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by bak3rmak3r** [dbweb-ch/ioBroker.rtspstream#6]
Hi! Thank you for sharing.
Is that still current? Should it be working?

I cannot get the webserver running.

Thank You!

**Comment by dbweb-ch** [comment]
Hi

Yes this is still working.

Mark Becker <notifications@github.com> schrieb am So., 19. Apr. 2020, 01:24:

**Comment by bak3rmak3r** [comment]
Thank you for your reply. Could you giva me a hint where i would find logs to debug why there is no webserver starting / answering on the definded port? Best regards!

**Comment by bak3rmak3r** [comment]
(index):5 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
WebAudioOut @ (index):5
Player @ (index):1
(anonymous) @ (index):6

(index):1 WebSocket connection to 'ws://172.16.0.31:554/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by dbweb-ch** [comment]
What does the ioBroker log say? 
There should be several entrys at "info"-Loglevel which tells "Start stream on"

Also you need to make sure to set "StartStream" to true in ioBroker.

**Comment by bak3rmak3r** [comment]
> 

host.iobroker | 2020-04-20 21:34:56.980 | error | Caught by controller[5]: configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --
-- | -- | -- | --
host.iobroker | 2020-04-20 21:34:56.980 | error | Caught by controller[4]: built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
host.iobroker | 2020-04-20 21:34:56.980 | error | Caught by controller[2]: Copyright (c) 2000-2019 the FFmpeg developers
host.iobroker | 2020-04-20 21:34:56.980 | error | Caught by controller[1]: ffmpeg version 3.4.6-0ubuntu0.18.04.1
host.iobroker | 2020-04-20 21:34:56.980 | error | Caught by controller[0]: port: 554 }
host.iobroker | 2020-04-20 21:34:56.980 | error | Caught by controller[0]: address: '::',
host.iobroker | 2020-04-20 21:34:56.980 | error | Caught by controller[0]: syscall: 'listen',
host.iobroker | 2020-04-20 21:34:56.980 | error | Caught by controller[0]: errno: 'EADDRINUSE',
host.iobroker | 2020-04-20 21:34:56.980 | error | Caught by controller[0]: code: 'EADDRINUSE',

**Comment by bak3rmak3r** [comment]
Am i getting it wrong? I am using TcpPort 554 on 2 streams as they are default port for rtsp an 2 different ports as webserver port.

**Comment by bak3rmak3r** [comment]
I get it up and running with 2 instances. That also fine :) Thank you for this adapter!

**Comment by dbweb-ch** [comment]
No you need to use different port for 2 streams. This is not the port of
your stream but the port of the stream for the websocket, so this does not
have to be the same as your camera uses.
