### ISSUE TITLE
automatic reload

### ISSUE THREAD

**Issue by bak3rmak3r** [dbweb-ch/ioBroker.rtspstream#7]
As streams are running a little our of sync getting the rtsp stream, republishing it through http and including it by iframe, i found that an automatic refresh every 5 minutes is a simple way to catch up again. Having that inside the rtspStream plugin just produces an very short blink of the stream that you hardly recognize where as reloading the site that is including the streams takes way longer.

Maybe it can become an option to activate in stream settings.

I just did the following inside the main.js and that really did the trick for me:

`let dataPointView1 = '<head><meta http-equiv="refresh" content=600"></head><body><canvas id="video-can$`

**Comment by dbweb-ch** [comment]
With your script "meta-refresh" you are doing nothing else than refreshing the page. How did you integrate the streams into your view? If you integrated them as iframe-Widget, you just can setup a refresh on those by setting "Refresh Time" and it should have the same effect.

**Comment by bak3rmak3r** [comment]
Yes, i know some html :)
I just wanted to state that i do wonder that the stream is running out of sync. May be you got an idea what could be the reason for that.

But, as mentioned, ther refresh is also fine for me.
