### ISSUE TITLE
uninstall impossible

### ISSUE THREAD

**Issue by bak3rmak3r** [dbweb-ch/ioBroker.rtspstream#8]
Hi!

As many are still using your alpha i like to ask if you might check why uninstallment is not possible with current iobroker version:

https://forum.iobroker.net/topic/27302/test-adapter-rtspstream-v0-0-x-github/85

Thank you in advance!

**Comment by dbweb-ch** [comment]
I checked up the code, but as far as I can see, this could not have to do anything with the adapter. There is nothing special in this adapter during the deinstallation process. Do you have other adapters where you have the same problem?

**Comment by bak3rmak3r** [comment]
Nope. Just this adapter. And as i really do use it everyday and got new cameras it would be great if you could check again. I would really appreciate.

**Comment by bak3rmak3r** [comment]
Someone wrote that issue is due to the capital S in the adapter name. Any idea so far?
https://forum.iobroker.net/topic/27302/test-adapter-rtspstream-v0-0-x-github/117

**Comment by dbweb-ch** [comment]
made a new version where all is lowercase now, so shouldn't be a problem for new installations anymore.

**Comment by emeins** [comment]
Sounds good, the installation and de-installation of the **_new_** adapter is working well. But how to clean up the old one?
![image](https://user-images.githubusercontent.com/17033201/103533010-a1179f80-4e8c-11eb-9f52-968324c99796.png)

**Comment by dbweb-ch** [comment]
Did you try the tips from jey cee in the forum? I don't have any other tips, sorry, but feel free to ask the forum again.
